resources:
- repo: self

name: $(Version)$(Rev:.r)

trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - 'master'

jobs:
- job: Extension
  pool:
    vmImage: macOS 10.13
    demands:
    - npm
    - node.js

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.12.0"

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false

  - task: Gulp@0
    displayName: 'gulp build'

  - task: CopyFiles@2
    displayName: 'Copy Files to staging'
    inputs:
      Contents: '**/*.vsix'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'